### ISSUE TITLE
Display the current date, time and timezone of the browser

### ISSUE THREAD

**Issue by jeantil** [timovn/MyWebTools#2]
Hello, 

Thanks for this tool it's really handy ! I would very much appreciate if the diagnostic page displayed the date time and timezone of the system in addition to the existing informations.

Thank you !

**Comment by timovn** [comment]
Done in commit #c3ec5b0

Live here : https://lehollandaisvolant.net/tout/tools/browser/ (right under UserAgent).

**Comment by jeantil** [comment]
Thanks!

Le ven. 29 nov. 2019 à 16:48, timo van neerden <notifications@github.com> a
écrit :
